default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

test:
  <<: *default
  database: db/test.sqlite3


# development:
#   adapter: mysql2
#   encoding: utf8
#   database: rails
#   pool: 5
#   username: root
#   password: root
#   collation: utf8_general_ci

# production:
#   adapter: mysql2
#   encoding: utf8
#   database: rails
#   pool: 5
#   username: root
#   password: root
#   collation: utf8_general_ci

# default: &default
#   adapter: postgresql
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   encoding: unicode
#   database: dpa_development
#   pool: 5
#   username: <%= ENV['DB_ENV_POSTGRESQL_USER'] %>
#   password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] %>
#   host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>

# test:
#   <<: *default
#   encoding: unicode
#   database: dpa_test
#   pool: 5
#   username: <%= ENV['DB_DATABASE_USERNAME'] %>
#   password: <%= ENV['DB_DATABASE_PASSWORD'] %>
#   host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
